# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureRmPipeline-comm'
    subscriptionId: 'ea9f04d5-f207-419d-8685-51eb6288f1e1'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'AzureRmPipeline-rg'
    location: 'Australia East'
    templateLocation: 'Linked artifact'
    csmFile: 'CreateWebApp/azuredeploy.json'
    overrideParameters: '-projectName mvrpipeline -linkedTemplateUri https://github.com/someone-au/azure-rm-pipeline-reop/blob/master/CreateWebApp/linkedStorageAccount.json'
    deploymentMode: 'Incremental'
